// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXLN0CAGq9nE_XIC6nsPvMpDQZ06nvA0E',
    appId: '1:266181853481:web:4b7c22678df349b8197738',
    messagingSenderId: '266181853481',
    projectId: 'flutteractivityapp',
    authDomain: 'flutteractivityapp.firebaseapp.com',
    storageBucket: 'flutteractivityapp.firebasestorage.app',
    measurementId: 'G-PFWJQGBEF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGFnkAcZzn-GOFCL5pya-YJ5RXTuJa2io',
    appId: '1:266181853481:android:551bc63afcbbb2f8197738',
    messagingSenderId: '266181853481',
    projectId: 'flutteractivityapp',
    storageBucket: 'flutteractivityapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYlWo6oLnCPfzR6TwpezBNDkgU0J7Rqr0',
    appId: '1:266181853481:ios:a8251ce8a262d35a197738',
    messagingSenderId: '266181853481',
    projectId: 'flutteractivityapp',
    storageBucket: 'flutteractivityapp.firebasestorage.app',
    androidClientId: '266181853481-k86cv725fivavk26usdejuf69gilcr1o.apps.googleusercontent.com',
    iosClientId: '266181853481-s46af50u7r78jjiad6c2894lanhadnq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterActivityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYlWo6oLnCPfzR6TwpezBNDkgU0J7Rqr0',
    appId: '1:266181853481:ios:a8251ce8a262d35a197738',
    messagingSenderId: '266181853481',
    projectId: 'flutteractivityapp',
    storageBucket: 'flutteractivityapp.firebasestorage.app',
    androidClientId: '266181853481-k86cv725fivavk26usdejuf69gilcr1o.apps.googleusercontent.com',
    iosClientId: '266181853481-s46af50u7r78jjiad6c2894lanhadnq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterActivityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXLN0CAGq9nE_XIC6nsPvMpDQZ06nvA0E',
    appId: '1:266181853481:web:3a5931aebd2a9b31197738',
    messagingSenderId: '266181853481',
    projectId: 'flutteractivityapp',
    authDomain: 'flutteractivityapp.firebaseapp.com',
    storageBucket: 'flutteractivityapp.firebasestorage.app',
    measurementId: 'G-HR1DVT4TJB',
  );

}